FORMAT: 1A

# Huddle API
Documentation for the development version of the Huddle APIs.

# Group Companies
Companies related resources of the **Huddle API**.

## Companies Collection [/people/companies]
### List all companies [GET]
+ Response 200 (application/vnd.huddle.data+json)

    + Body

            {
                "links": [
                    {
                        "rel": "self",
                        "href": "https://api.huddle.net/people/companies"
                    }
                ],
                "companies": [
                    {
                        "links": [
                            {
                                "rel": "self",
                                "href": "https://api.huddle.net/people/company/123"
                            },
                            {
                                "rel": "members",
                                "href": "https://api.huddle.net/people/companies/123/members"
                            },
                            {
                                "rel": "workspaces",
                                "href": "https://api.huddle.net/people/companies/123/workspaces"
                            },
                            {
                                "rel": "managers",
                                "href": "https://api.huddle.net/people/companies/123/managers"
                            },
                            {
                                "rel": "bulk-delete",
                                "href": "https://api.huddle.net/people/companies/123/bulkdelete"
                            }
                        ],
                        "name": "Huddle"
                    }
                ]
            }

## Company [/people/companies/{id}]

+ Parameters
    + id (required, number, `123`) ... Numeric `id` of the Company resource to perform action with.

### Retrieve a Company [GET]
+ Response 200 (application/vnd.huddle.data+json)

    + Body

            {
                "links": [
                    {
                        "rel": "self",
                        "href": "https://api.huddle.net/people/company/123"
                    },
                    {
                        "rel": "members",
                        "href": "https://api.huddle.net/people/companies/123/members"
                    },
                    {
                        "rel": "workspaces",
                        "href": "https://api.huddle.net/people/companies/123/workspaces"
                    },
                    {
                        "rel": "managers",
                        "href": "https://api.huddle.net/people/companies/123/managers"
                    },
                    {
                        "rel": "bulk-delete",
                        "href": "https://api.huddle.net/people/companies/123/bulkdelete"
                    }
              ],
              "name": "Huddle"
            }
